# Generated by Django 2.1.3 on 2018-11-16 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexaoRegiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='OpiniaoConexao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha_usuario', models.CharField(choices=[('0', 'Ruim'), ('1', 'Neutra'), ('2', 'Boa')], max_length=10, verbose_name='opiniao_conexao_regiao')),
                ('conexao_regiao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regionamento.ConexaoRegiao')),
                ('user_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpiniaoRegiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha_usuario', models.CharField(choices=[('0', 'Ruim'), ('1', 'Neutra'), ('2', 'Boa')], max_length=10, verbose_name='opiniao_regiao')),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
        ),
        migrations.AddField(
            model_name='opiniaoregiao',
            name='regiao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regionamento.Regiao'),
        ),
        migrations.AddField(
            model_name='opiniaoregiao',
            name='user_criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conexaoregiao',
            name='reg1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiao_pai', to='regionamento.Regiao'),
        ),
        migrations.AddField(
            model_name='conexaoregiao',
            name='reg2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiao_filho', to='regionamento.Regiao'),
        ),
    ]
