# Generated by Django 2.1.3 on 2018-11-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexaoregiao',
            name='nome',
            field=models.CharField(default='Reg', max_length=100, verbose_name='nome'),
        ),
    ]
