# Generated by Django 2.1.3 on 2018-11-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg_syst',
            name='texto',
            field=models.CharField(default='', max_length=500, verbose_name='nome'),
        ),
    ]
