# Generated by Django 2.1.3 on 2018-11-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_auto_20181117_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg_syst',
            name='gender',
        ),
        migrations.AddField(
            model_name='msg_syst',
            name='tipo_mensagem',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Alerta'), ('C', 'Compra')], default='A', max_length=9, verbose_name='tipo_mensagem'),
        ),
    ]
