# Generated by Django 2.1.3 on 2018-11-22 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensagens', '0003_auto_20181122_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSG_PARA_SYST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mensagem', models.CharField(choices=[('S', 'Sugestão'), ('R', 'Reclamação'), ('O', 'Outros')], default='S', max_length=9, verbose_name='tipo_mensagem')),
                ('texto', models.CharField(default='', max_length=500, verbose_name='nome')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data_criacao_mensagem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
