# Generated by Django 2.1.3 on 2018-11-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0004_msg_para_syst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg_para_syst',
            name='texto',
            field=models.CharField(default='', max_length=500, verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='msg_syst',
            name='texto',
            field=models.CharField(default='', max_length=500, verbose_name='texto'),
        ),
    ]
