# Generated by Django 2.1.3 on 2018-11-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_perfil', '0002_auto_20181118_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='idiomas',
            field=models.ManyToManyField(blank=True, default=None, to='regionamento.Idioma'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='regioes',
            field=models.ManyToManyField(blank=True, default=None, to='regionamento.Regiao'),
        ),
    ]
