# Generated by Django 2.1.3 on 2018-11-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_perfil', '0003_auto_20181118_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='premium'),
        ),
    ]
