# Generated by Django 2.1.3 on 2018-11-16 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regionamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpiniaoPergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha_usuario', models.CharField(choices=[('0', 'Mal formulada'), ('1', 'Escrita sem significado')], max_length=10, verbose_name='reclamacao')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data_criacao_opiniao')),
            ],
        ),
        migrations.CreateModel(
            name='OpiniaoQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha_usuario', models.CharField(choices=[('0', 'Não existe resposta correta'), ('1', 'Tempo nao suficiente')], max_length=10, verbose_name='reclamacao')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data_criacao_opiniao')),
            ],
        ),
        migrations.CreateModel(
            name='OpiniaoResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha_usuario', models.CharField(choices=[('0', 'Mal formulada'), ('1', 'Escrita sem significado')], max_length=10, verbose_name='reclamacao')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data_criacao_opiniao')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrativa', models.CharField(max_length=100, verbose_name='texto')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.CharField(choices=[('F', 'Facil'), ('D', 'Dificil')], max_length=9, verbose_name='dificuldade')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data_criacao')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrativa', models.CharField(max_length=100, verbose_name='texto')),
            ],
        ),
        migrations.CreateModel(
            name='PrototipoQuestao',
            fields=[
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='triviamente.Questao')),
                ('escolha_usuario', models.CharField(choices=[('0', 'Ruim'), ('1', 'Neutra'), ('2', 'Boa')], max_length=10, verbose_name='reclamacao')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data_criacao')),
                ('user_criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triviamente.Pergunta'),
        ),
        migrations.AddField(
            model_name='questao',
            name='regiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regionamento.Regiao'),
        ),
        migrations.AddField(
            model_name='questao',
            name='resp1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resposta_1', to='triviamente.Resposta'),
        ),
        migrations.AddField(
            model_name='questao',
            name='resp2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resposta_2', to='triviamente.Resposta'),
        ),
        migrations.AddField(
            model_name='questao',
            name='resp3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resposta_3', to='triviamente.Resposta'),
        ),
        migrations.AddField(
            model_name='questao',
            name='resp4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resposta_4', to='triviamente.Resposta'),
        ),
        migrations.AddField(
            model_name='questao',
            name='user_criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opiniaoresposta',
            name='resposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='triviamente.Resposta'),
        ),
        migrations.AddField(
            model_name='opiniaoresposta',
            name='user_criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opiniaoquestao',
            name='questao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='triviamente.Questao'),
        ),
        migrations.AddField(
            model_name='opiniaoquestao',
            name='user_criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opiniaopergunta',
            name='pergunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='triviamente.Pergunta'),
        ),
        migrations.AddField(
            model_name='opiniaopergunta',
            name='user_criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
