# Generated by Django 2.1.3 on 2018-11-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triviamente', '0004_auto_20181117_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='resp1',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='resp2',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='resp3',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='resp4',
        ),
        migrations.AddField(
            model_name='questao',
            name='respostas',
            field=models.ManyToManyField(blank=True, default=None, to='triviamente.Resposta'),
        ),
    ]
