# Generated by Django 2.1.3 on 2018-11-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triviamente', '0005_auto_20181118_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototipoquestao',
            name='escolha_usuario',
        ),
        migrations.RemoveField(
            model_name='prototipoquestao',
            name='user_criador',
        ),
        migrations.AddField(
            model_name='prototipoquestao',
            name='negativo',
            field=models.IntegerField(default=0, verbose_name='negativo'),
        ),
        migrations.AddField(
            model_name='prototipoquestao',
            name='positivo',
            field=models.IntegerField(default=0, verbose_name='positivo'),
        ),
    ]
