# Generated by Django 2.1.3 on 2018-11-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triviamente', '0006_auto_20181122_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_pergunta_ou_resposta',
            field=models.CharField(choices=[('0', 'Artes'), ('1', 'Ciencias'), ('2', 'Cotidiano'), ('3', 'Esportes'), ('4', 'Geografia'), ('5', 'Historia')], default='0', max_length=20, verbose_name='tipo_pergunta_ou_resposta'),
        ),
    ]
