# Generated by Django 2.1.3 on 2018-11-16 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triviamente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('value', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data_criacao')),
                ('custo', models.IntegerField(choices=[(1, 'CUSTO_ZERO'), (2, 'CUSTO_PEQUENO'), (3, 'CUSTO_MEDIO'), (4, 'CUSTO_GRANDE'), (5, 'CUSTO_ENORME'), (6, 'CUSTO_ABSURDO')], default=2, verbose_name='custo')),
                ('carteira_se_chegar_aqui_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteira_se_chegar_aqui_1', to='value.Carteira')),
                ('carteira_se_chegar_aqui_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteira_se_chegar_aqui_2', to='value.Carteira')),
                ('carteira_se_chegar_aqui_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteira_se_chegar_aqui_3', to='value.Carteira')),
            ],
        ),
        migrations.CreateModel(
            name='SUQuestionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(blank=True, verbose_name='data_resposta')),
                ('carteira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='value.Carteira')),
                ('questao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triviamente.Questao')),
                ('resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='q1_categoria_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_1_categoria_1', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q1_categoria_2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_1_categoria_2', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q1_categoria_3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_1_categoria_3', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q1_categoria_4',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_1_categoria_4', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q1_categoria_5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_1_categoria_5', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q2_categoria_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_2_categoria_1', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q2_categoria_2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_2_categoria_2', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q2_categoria_3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_2_categoria_3', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q2_categoria_4',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_2_categoria_4', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q2_categoria_5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_2_categoria_5', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q3_categoria_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_3_categoria_1', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q3_categoria_2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_3_categoria_2', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q3_categoria_3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_3_categoria_3', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q3_categoria_4',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_3_categoria_4', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='q3_categoria_5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questao_3_categoria_5', to='stacksup.SUQuestionLog'),
        ),
        migrations.AddField(
            model_name='partida',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_partida', to=settings.AUTH_USER_MODEL),
        ),
    ]
