# Generated by Django 2.1.3 on 2018-11-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacksup', '0004_auto_20181123_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suquestionlog',
            name='data_resposta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data_resposta'),
        ),
    ]
