# Generated by Django 2.1.3 on 2018-11-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacksup', '0006_auto_20181123_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='aberta',
            field=models.BooleanField(default=True),
        ),
    ]
