# Generated by Django 2.1.3 on 2018-11-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0002_carta_boost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='comentario',
            field=models.CharField(default='carteira_usuario', max_length=100, verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='moedas',
            field=models.IntegerField(default=1000, verbose_name='moedas'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='pontos',
            field=models.IntegerField(default=0, verbose_name='pontos'),
        ),
    ]
