# Generated by Django 2.1.3 on 2018-11-22 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0003_auto_20181121_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_carteira', to=settings.AUTH_USER_MODEL),
        ),
    ]
